/*
 * Copyright 2018 MovingBlocks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.terasology.web.serverAdminManagement;

import java.util.Objects;

/**
 * This class is a simple container that follows the pair pattern.
 * @param <T> the first part of the pair.
 * @param <U> the second part of the pair.
 */
public class IdPermissionPair<T, U> {

    private T id;
    private U permissions;

    public IdPermissionPair(T id, U permissions) {
        this.id = id;
        this.permissions = permissions;
    }

    public T getId() {
        return id;
    }

    public U getPermissions() {
        return permissions;
    }

    // Autogenerated by Intellij and modified for style.
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IdPermissionPair<?, ?> that = (IdPermissionPair<?, ?>) o;
        return Objects.equals(id, that.id) && Objects.equals(permissions, that.permissions);
    }

    // Autogenerated by Intellij and modified for style.
    @Override
    public int hashCode() {
        return Objects.hash(id, permissions);
    }

    // Autogenerated by Intellij and modified for style.
    @Override
    public String toString() {
        return "IdPermissionPair{" + "id=" + id + ", permissions=" + permissions + "}";
    }
}
